[package]
name = "lyrebird"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = "3.2.5"
cfg-if = "1.0.0"
serde_json = "1.0.0"
time = { version = "0.3.9", features = ["formatting"] }

[target.'cfg(unix)'.dependencies]
libc = "0.2.126"

[target.'cfg(windows)'.dependencies]
winapi = "0.3.9"
